# Pour Extension VS Code REST CLIENT

# Routes pour les missions
### GET missions/all
GET http://localhost:3000/missions/all

### GET missions/mission/idMission
GET http://localhost:3000/missions/mission/CTL01-TVA-02

### GET missions/collab/idCollab
GET http://localhost:3000/missions/collab/C02


### GET missions/client/idClient
GET http://localhost:3000/missions/client/CTL01
